spring:
  application:
    name: myProductsTestYaml
  datasource:
    url: jdbc:postgresql://localhost:5432/my_products_db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect